server:
  port: 7070
spring:
  application:
    name: auth-client
  security:
    oauth2:
      client:
        provider:
          auth-server:
            issuer-uri: http://127.0.0.1:8080
        registration:
          auth_server:
            client-id: tajjiboma
            client-secret: tuzid
            client-name: Custom
            provider: auth-server
            client-authentication-method: client_secret_basic
            redirect-uri: https://google.com/
            scope:
              - openid
