server:
  port: 8000
  error:
    include-message: ALWAYS
    include-stacktrace: always
spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    sql:
      init-mode: always
      schema: classpath:db/migration/*.sql

jwt:
  secret-key: AbCdEf1234567890GhiJklMnoPqrStuvWxyz0123456789AbCdEfGhiJklMnoPqrStuvWxyz
