server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
spring:
  application:
    name: order-service

  lifecycle:
    timeout-per-shutdown-phase: 15s

  cloud:
    function:
      definition: dispatchOrder
    stream:
      bindings:
        dispatchOrder-in-0:
          destination: order-dispatched
          group: { spring.application.name }

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s

  r2dbc:
    url: r2dbc:postgresql://localhost:55000/test
    username: test
    password: test
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/PolarBookshop #A URI to the relevant authorization server, including Keycloak

  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:55000/test


